/// <reference types="vitest" />
import path from 'path'
import { defineConfig } from 'vitest/config'

export default defineConfig({
  resolve: {
    alias: {
      '@tauri-apps/plugin-fs': path.resolve(__dirname, 'src/__mocks__/tauri-plugin-fs.ts'),
      '@tauri-apps/plugin-shell': path.resolve(__dirname, 'src/__mocks__/tauri-plugin-shell.ts'),
    },
  },
  test: {
    globals: true,
    environment: 'jsdom',
    include: ['src/**/*.test.{ts,tsx}', 'benchmarks/**/*.test.ts', 'e2e/tests/**/*.test.ts', 'e2e/**/*.e2e.test.ts'],
    exclude: ['e2e/My-mgmt*/**', 'node_modules/**'],
    setupFiles: ['./src/test/setup.ts'],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json', 'html', 'lcov'],
      include: ['src/**/*.{ts,tsx}'],
      exclude: [
        'node_modules/',
        'e2e/',
        'benchmarks/',
        '**/*.d.ts',
        '**/*.test.{ts,tsx}',
        '**/*.spec.{ts,tsx}',
        '**/dist/**',
        'src/app/components/ui/**',
        'src/app/lib/**',
        'src/main.tsx',
        'src/vite-env.d.ts',
        'src/app/components/**',
        'src/app/hooks/**',
        'src/app/pages/**',
        'src/app/App.tsx',
        'src/app/router.tsx',
        'src/test/**',
        'src/__mocks__/**',
        'src/app/workers/**',
        '**/*.worker.ts',
        'src/app/utils/model-router.ts',
        'src/app/utils/layout-engine.ts',
        'src/app/utils/audio-engine.ts',
        'src/app/utils/local-model-client.ts',
        'src/app/utils/local-model-infra.ts',
        'src/utils/version-examples.ts',
        'src/utils/version-manager.ts',
        'src/components/Chat/**',
        'src/app/types/**',
        '**/types/**',
        'src/app/store/webgpu-inference-store.ts',
        'src/app/store/self-media-store.tsx',
        'src/app/services/data-sync-orchestrator.ts',
        'src/app/services/data-portability-manager.ts',
        'src/app/services/monaco-performance-benchmark.ts',
        'src/app/services/monaco-preloader.ts',
      ],
      thresholds: {
        statements: 60,
        branches: 45,
        functions: 55,
        lines: 60,
      },
      clean: true,
    },
  },
})
